import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Todo/Navbar";
import Providers from "@/components/Todo/Providers";
import Footer from "@/components/Todo/Footer";
// import { Box } from "@mui/material";
// import { ThemeProvider } from '@mui/material/styles';
// import CssBaseline from '@mui/material/CssBaseline';
// import theme from '@/theme';
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
         <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-K3DXL0YBDR"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-K3DXL0YBDR');
          `}
        </Script>

      </head>




      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

        <header>
          <Navbar />
        </header>
        <main>
          <Providers>{children}</Providers>
        </main>

        <footer className="bg-slate-50 w-full">
          <Footer />
        </footer>

      </body>

    </html>
  );
}
